const TEMPLATES = {
  python_hello: {
    filename: "hello_world.py",
    content: `#!/usr/bin/env python3

def fancy_hello(name = "darling"):
    message = f"Hello, {name}! Zero Two is online."
    border = "=" * (len(message) + 2)
    return f"[{border}]\\n[{message}]\\n[{border}]"

if __name__ == "__main__":
    print(fancy_hello())
`
  },

  python_function: {
    filename: "example.py",
    content: `#!/usr/bin/env python3
"""Simple example function."""

def greet(name="friend"):
    """Greet someone."""
    return f"Hello, {name}!"

def add(a, b):
    """Add two numbers."""
    return a + b

if __name__ == "__main__":
    print(greet("Zero Two"))
    print(f"1 + 2 = {add(1, 2)}")
`
  },

  readme: {
    filename: "README.md",
    content: `# Project Name

A brief description of your project.

## Getting Started

### Prerequisites

- List requirements here

### Installation

\`\`\`bash
# Setup instructions
\`\`\`

## Usage

\`\`\`bash
# Example usage
\`\`\`

## Features

- Feature 1
- Feature 2
- Feature 3

## License

MIT - Generated by Zero Two
`
  },

  config_json: {
    filename: "config.json",
    content: JSON.stringify({
      name: "my-app",
      version: "1.0.0",
      settings: {
        debug: false,
        timeout: 5000,
        retries: 3
      }
    }, null, 2)
  },

  config_yaml: {
    filename: "config.yaml",
    content: `app:
  name: my-app
  version: "1.0.0"

settings:
  debug: false
  timeout: 5000
  retries: 3

logging:
  level: info
`
  },

  js_starter: {
    filename: "index.js",
    content: `/**
 * A simple Node.js starter file
 */

const http = require("http");

const hostname = "127.0.0.1";
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader("Content-Type", "text/plain");
  res.end("Hello from Zero Two!\\n");
});

server.listen(port, hostname, () => {
  console.log(\`Server running at http://\${hostname}:\${port}/\`);
});
`
  },

  bash_script: {
    filename: "script.sh",
    content: `#!/bin/bash

set -euo pipefail

echo "Starting script..."

# Add your commands here

echo "Done!"
`
  }
};

function generateTemplate(templateName, context = {}) {
  const template = TEMPLATES[templateName];
  if (!template) {
    throw new Error("Template not found: " + templateName);
  }
  return {
    content: template.content,
    filename: template.filename,
    mimeType: "text/plain"
  };
}

function listAvailableTemplates() {
  return Object.keys(TEMPLATES);
}

function getTemplateInfo(templateName) {
  const template = TEMPLATES[templateName];
  if (!template) {
    return null;
  }
  return {
    name: templateName,
    filename: template.filename,
    size: Buffer.byteLength(template.content, "utf8")
  };
}

module.exports = {
  generateTemplate,
  listAvailableTemplates,
  getTemplateInfo,
  TEMPLATES
};
